init:
	npm init -y
	npm i -D typescript tsc-watch eslint prettier eslint-config-prettier eslint-plugin-prettier @typescript-eslint/parser @typescript-eslint/eslint-plugin @types/node @types/express 
	npm i express dotenv 
	npx tsc --init
	npm i module-alias  
	npm i mongoose compression helmet cors
	npm i -D @types/compression @types/cors @types/morgan 
	npm i envalid
	npm i joi

###
# Extension: ESLint, Prettier, 